<a href="https://colab.research.google.com/github/Wikanda-Hongboonmee/DWDM21/blob/main/Project_DWDM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd  # pandas เป็น Package ที่ใช้เกี่ยวกับการจัดการข้อมูลที่เป็นตาราง , เรียกใช้โดยการ import แล้วตามด้วยชื่อ Package

In [2]:
from google.colab import drive  # เชื่อมต่อกับ google drive ที่เราเก็บข้อมูลไว้
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os # เป็น package ที่เอาไว้จัดการไฟล์และเอาไว้ดูที่มาของไฟล์หรือ path

In [4]:
path = '/content/drive/My Drive/DWDM2021_DATAPROJECT'

### **ชุดข้อมูลที่ 1 รับเรื่องร้องเรียน/แจ้งเบาะแสยาเสพติด**

In [5]:
data_01 = pd.read_csv(os.path.join(path,'รับเรื่องร้องเรียนยาเสพติด.csv')) # ไฟล์ที่เราต้องการ
data_01 # print data ดูว่ามันหน้าตาเป็นยังไง

    ปีงบประมาณ  ...  เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)
0         2563  ...                                              97.81
1         2563  ...                                             100.00
2         2563  ...                                              97.26
3         2563  ...                                              99.13
4         2563  ...                                             100.00
..         ...  ...                                                ...
72        2563  ...                                             100.00
73        2563  ...                                             100.00
74        2563  ...                                             100.00
75        2563  ...                                             100.00
76        2563  ...                                              93.52

[77 rows x 12 columns]

In [6]:
data_01 = data_01.sort_values(by=['รหัสจังหวัด'])
data_01

    ปีงบประมาณ  ...  เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)
76        2563  ...                                              93.52
0         2563  ...                                              97.81
1         2563  ...                                             100.00
2         2563  ...                                              97.26
3         2563  ...                                              99.13
..         ...  ...                                                ...
71        2563  ...                                             100.00
72        2563  ...                                             100.00
73        2563  ...                                             100.00
74        2563  ...                                             100.00
75        2563  ...                                             100.00

[77 rows x 12 columns]

In [7]:
data_01.isnull() # ตรงไหนเป็นช่องว่างจะขึ้นว่า True ตรงไหนไม่เป็นช่องว่างจะขึ้นว่า False

    ปีงบประมาณ  ...  เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)
76       False  ...                                              False
0        False  ...                                              False
1        False  ...                                              False
2        False  ...                                              False
3        False  ...                                              False
..         ...  ...                                                ...
71       False  ...                                              False
72       False  ...                                              False
73       False  ...                                              False
74       False  ...                                              False
75       False  ...                                              False

[77 rows x 12 columns]

In [8]:
data_01.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง

ปีงบประมาณ                                                                    False
รหัสจังหวัด                                                                   False
ชื่อจังหวัด                                                                   False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)                          False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)           False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (%)     False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง)                         False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง)          False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (%)    False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง)                           False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง)            False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)      False
dtype: bool

### **ชุดข้อมูลที่ 2 ปริมาณของกลางยาเสพติด**

In [9]:
data_02 = pd.read_csv(os.path.join(path,'ปริมาณของกลางยาเสพติด.csv')) # ไฟล์ที่เราต้องการ
data_02 # print data ดูว่ามันหน้าตาเป็นยังไง

    ปีงบประมาณ  รหัสจังหวัด  ... โคเคน (กิโลกรัม)  กระท่อม (กิโลกรัม)
0         2563           32  ...            0.000            35.07000
1         2563           41  ...            0.000             0.26000
2         2563           49  ...            0.000             0.58500
3         2563           47  ...            0.000            24.53000
4         2563           46  ...            0.000             0.00000
..         ...          ...  ...              ...                 ...
72        2563           92  ...            0.000          1772.45500
73        2563           93  ...            0.000          1242.31250
74        2563           94  ...            0.000          5950.30800
75        2563           95  ...            0.000          4043.89700
76        2563           10  ...            0.049          2755.81611

[77 rows x 10 columns]

In [10]:
data_02 = data_02.sort_values(by=['รหัสจังหวัด'])
data_02

    ปีงบประมาณ  รหัสจังหวัด  ... โคเคน (กิโลกรัม)  กระท่อม (กิโลกรัม)
76        2563           10  ...            0.049          2755.81611
24        2563           11  ...            0.000           332.85821
25        2563           12  ...            0.030           626.33734
26        2563           13  ...            0.000           981.02860
27        2563           14  ...            0.000           932.65946
..         ...          ...  ...              ...                 ...
72        2563           92  ...            0.000          1772.45500
73        2563           93  ...            0.000          1242.31250
74        2563           94  ...            0.000          5950.30800
75        2563           95  ...            0.000          4043.89700
69        2563           96  ...            0.000          5569.70900

[77 rows x 10 columns]

In [11]:
data_02.isnull() # ตรงไหนเป็นช่องว่างจะขึ้นว่า True ตรงไหนไม่เป็นช่องว่างจะขึ้นว่า False

    ปีงบประมาณ  รหัสจังหวัด  ...  โคเคน (กิโลกรัม)  กระท่อม (กิโลกรัม)
76       False        False  ...             False               False
24       False        False  ...             False               False
25       False        False  ...             False               False
26       False        False  ...             False               False
27       False        False  ...             False               False
..         ...          ...  ...               ...                 ...
72       False        False  ...             False               False
73       False        False  ...             False               False
74       False        False  ...             False               False
75       False        False  ...             False               False
69       False        False  ...             False               False

[77 rows x 10 columns]

In [12]:
data_02.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง

ปีงบประมาณ              False
รหัสจังหวัด             False
ชื่อจังหวัด             False
ยาบ้า (เม็ด)            False
ไอซ์ (กิโลกรัม)         False
กัญชาแห้ง (กิโลกรัม)    False
เฮโรอีน (กิโลกรัม)      False
คีตามีน (กิโลกรัม)      False
โคเคน (กิโลกรัม)        False
กระท่อม (กิโลกรัม)      False
dtype: bool

### **ชุดข้อมูลที่ 3 จำนวนคดี ผู้ต้องหาคดียาเสพติด**

In [13]:
data_03 = pd.read_csv(os.path.join(path,'คดีผู้องหาคดียาเสพติด.csv')) # ไฟล์ที่เราต้องการ
data_03 # print data ดูว่ามันหน้าตาเป็นยังไง

    ปีงบประมาณ  ...  จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)
0         2563  ...                                1198
1         2563  ...                                 596
2         2563  ...                                1433
3         2563  ...                                 913
4         2563  ...                                1857
..         ...  ...                                 ...
72        2563  ...                                3043
73        2563  ...                                1619
74        2563  ...                                2164
75        2563  ...                                 834
76        2563  ...                                 881

[77 rows x 23 columns]

In [14]:
data_03 = data_03.sort_values(by=['รหัสจังหวัด'])
data_03

    ปีงบประมาณ  ...  จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)
47        2563  ...                                5685
53        2563  ...                                2999
49        2563  ...                                1448
50        2563  ...                                1873
51        2563  ...                                1650
..         ...  ...                                 ...
40        2563  ...                                1346
43        2563  ...                                1208
42        2563  ...                                1624
44        2563  ...                                1161
41        2563  ...                                1230

[77 rows x 23 columns]

In [15]:
data_03.isnull() # ตรงไหนเป็นช่องว่างจะขึ้นว่า True ตรงไหนไม่เป็นช่องว่างจะขึ้นว่า False

    ปีงบประมาณ  ...  จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)
47       False  ...                               False
53       False  ...                               False
49       False  ...                               False
50       False  ...                               False
51       False  ...                               False
..         ...  ...                                 ...
40       False  ...                               False
43       False  ...                               False
42       False  ...                               False
44       False  ...                               False
41       False  ...                               False

[77 rows x 23 columns]

In [16]:
data_03.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง

ปีงบประมาณ                                    False
รหัสจังหวัด                                   False
ชื่อจังหวัด                                   False
จำนวนคดีทั้งหมด (คดี)                         False
จำนวนผู้ต้องหาทั้งหมด (คน)                    False
จำนวนคดีเสพ (คดี)                             False
จำนวนผู้ต้องหาคดีเสพ (คน)                     False
จำนวนคดีครอบครอง (คดี)                        False
จำนวนผู้ต้องหาคดีครอบครอง (คน)                False
จำนวนคดีครอบครองเพื่อจำหน่าย (คดี)            False
จำนวนผู้ต้องหาคดีครอบครองเพื่อจำหน่าย (คน)    False
จำนวนคดีจำหน่าย (คดี)                         False
จำนวนผู้ต้องหาคดีจำหน่าย (คน)                 False
จำนวนคดีผลิต (คดี)                            False
จำนวนผู้ต้องหาคดีผลิต (คน)                    False
จำนวนคดีนำเข้า (คดี)                           True
จำนวนผู้ต้องหาคดีนำเข้า (คน)                   True
จำนวนคดีส่งออก (คดี)                          False
จำนวนผู้ต้องหาคดีส่งออก (คน)                  False
จำนวนคดีสมคบ (คดี)                             True
จำนวนผู้ต้องหาคดีสมคบ (คน)                     True
จำนวนคดี 5 ข้อหาหลัก (คดี)                    False
จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)            False
dtype: bool

In [17]:
data_03nomissing = data_03.dropna()
data_03nomissing

    ปีงบประมาณ  ...  จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)
47        2563  ...                                5685
53        2563  ...                                2999
48        2563  ...                                 564
60        2563  ...                                 367
62        2563  ...                                 651
64        2563  ...                                 783
66        2563  ...                                2792
70        2563  ...                                1427
69        2563  ...                                2484
72        2563  ...                                3043
71        2563  ...                                 855
76        2563  ...                                 881
74        2563  ...                                2164
3         2563  ...                                 913
5         2563  ...                                 768
0         2563  ...                                1198
2         2563  ...                                1433
4         2563  ...                                1857
75        2563  ...                                 834
1         2563  ...                                 596
9         2563  ...                                3234
8         2563  ...                                1910
13        2563  ...                                 160
17        2563  ...                                 543
29        2563  ...                                 976
25        2563  ...                                1022
32        2563  ...                                1037
27        2563  ...                                1130
36        2563  ...                                 731
37        2563  ...                                2164
38        2563  ...                                 511
45        2563  ...                                3366
46        2563  ...                                 966
41        2563  ...                                1230

[34 rows x 23 columns]

In [18]:
data_03.shape

(77, 23)

In [19]:
data_03nomissing.shape

(34, 23)

In [20]:
data_01.shape

(77, 12)

In [21]:
data_02.shape

(77, 10)

In [22]:
data_03nomissing.shape

(34, 23)

In [23]:
data_02.drop(['ปีงบประมาณ','ชื่อจังหวัด'],axis=1, inplace=True)
data_02

    รหัสจังหวัด  ยาบ้า (เม็ด)  ...  โคเคน (กิโลกรัม)  กระท่อม (กิโลกรัม)
76           10       1820511  ...             0.049          2755.81611
24           11        168905  ...             0.000           332.85821
25           12        878015  ...             0.030           626.33734
26           13       1210734  ...             0.000           981.02860
27           14       6366864  ...             0.000           932.65946
..          ...           ...  ...               ...                 ...
72           92       2489255  ...             0.000          1772.45500
73           93        630449  ...             0.000          1242.31250
74           94       3526543  ...             0.000          5950.30800
75           95       1769054  ...             0.000          4043.89700
69           96       3422397  ...             0.000          5569.70900

[77 rows x 8 columns]

In [24]:
merge_2table = data_01.merge(data_02,how='left', left_on='รหัสจังหวัด',right_on='รหัสจังหวัด')
merge_2table

    ปีงบประมาณ  รหัสจังหวัด  ... โคเคน (กิโลกรัม)  กระท่อม (กิโลกรัม)
0         2563           10  ...            0.049          2755.81611
1         2563           11  ...            0.000           332.85821
2         2563           12  ...            0.030           626.33734
3         2563           13  ...            0.000           981.02860
4         2563           14  ...            0.000           932.65946
..         ...          ...  ...              ...                 ...
72        2563           92  ...            0.000          1772.45500
73        2563           93  ...            0.000          1242.31250
74        2563           94  ...            0.000          5950.30800
75        2563           95  ...            0.000          4043.89700
76        2563           96  ...            0.000          5569.70900

[77 rows x 19 columns]

In [25]:
merge_2table.isnull() # ตรงไหนเป็นช่องว่างจะขึ้นว่า True ตรงไหนไม่เป็นช่องว่างจะขึ้นว่า False

    ปีงบประมาณ  รหัสจังหวัด  ...  โคเคน (กิโลกรัม)  กระท่อม (กิโลกรัม)
0        False        False  ...             False               False
1        False        False  ...             False               False
2        False        False  ...             False               False
3        False        False  ...             False               False
4        False        False  ...             False               False
..         ...          ...  ...               ...                 ...
72       False        False  ...             False               False
73       False        False  ...             False               False
74       False        False  ...             False               False
75       False        False  ...             False               False
76       False        False  ...             False               False

[77 rows x 19 columns]

In [26]:
merge_2table.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง

ปีงบประมาณ                                                                    False
รหัสจังหวัด                                                                   False
ชื่อจังหวัด                                                                   False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)                          False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)           False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (%)     False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง)                         False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง)          False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (%)    False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง)                           False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง)            False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)      False
ยาบ้า (เม็ด)                                                                  False
ไอซ์ (กิโลกรัม)                                                               False
กัญชาแห้ง (กิโลกรัม)                                                          False
เฮโรอีน (กิโลกรัม)                                                            False
คีตามีน (กิโลกรัม)                                                            False
โคเคน (กิโลกรัม)                                                              False
กระท่อม (กิโลกรัม)                                                            False
dtype: bool

In [27]:
data_03nomissing.drop(['ปีงบประมาณ','ชื่อจังหวัด'],axis=1, inplace=True)
data_03nomissing

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

    รหัสจังหวัด  ...  จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)
47           10  ...                                5685
53           11  ...                                2999
48           18  ...                                 564
60           23  ...                                 367
62           25  ...                                 651
64           27  ...                                 783
66           30  ...                                2792
70           32  ...                                1427
69           33  ...                                2484
72           34  ...                                3043
71           37  ...                                 855
76           38  ...                                 881
74           40  ...                                2164
3            42  ...                                 913
5            43  ...                                 768
0            44  ...                                1198
2            45  ...                                1433
4            47  ...                                1857
75           48  ...                                 834
1            49  ...                                 596
9            50  ...                                3234
8            57  ...                                1910
13           58  ...                                 160
17           63  ...                                 543
29           70  ...                                 976
25           71  ...                                1022
32           72  ...                                1037
27           77  ...                                1130
36           82  ...                                 731
37           83  ...                                2164
38           85  ...                                 511
45           90  ...                                3366
46           91  ...                                 966
41           96  ...                                1230

[34 rows x 21 columns]

In [28]:
merge_3table = merge_2table.merge(data_03nomissing,how='left', left_on='รหัสจังหวัด',right_on='รหัสจังหวัด')
merge_3table

    ปีงบประมาณ  ...  จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)
0         2563  ...                              5685.0
1         2563  ...                              2999.0
2         2563  ...                                 NaN
3         2563  ...                                 NaN
4         2563  ...                                 NaN
..         ...  ...                                 ...
72        2563  ...                                 NaN
73        2563  ...                                 NaN
74        2563  ...                                 NaN
75        2563  ...                                 NaN
76        2563  ...                              1230.0

[77 rows x 39 columns]

In [29]:
merge_3table.isnull()

    ปีงบประมาณ  ...  จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)
0        False  ...                               False
1        False  ...                               False
2        False  ...                                True
3        False  ...                                True
4        False  ...                                True
..         ...  ...                                 ...
72       False  ...                                True
73       False  ...                                True
74       False  ...                                True
75       False  ...                                True
76       False  ...                               False

[77 rows x 39 columns]

In [30]:
merge_3table.isnull().any()

ปีงบประมาณ                                                                    False
รหัสจังหวัด                                                                   False
ชื่อจังหวัด                                                                   False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)                          False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)           False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (%)     False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง)                         False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง)          False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (%)    False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง)                           False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง)            False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)      False
ยาบ้า (เม็ด)                                                                  False
ไอซ์ (กิโลกรัม)                                                               False
กัญชาแห้ง (กิโลกรัม)                                                          False
เฮโรอีน (กิโลกรัม)                                                            False
คีตามีน (กิโลกรัม)                                                            False
โคเคน (กิโลกรัม)                                                              False
กระท่อม (กิโลกรัม)                                                            False
จำนวนคดีทั้งหมด (คดี)                                                          True
จำนวนผู้ต้องหาทั้งหมด (คน)                                                     True
จำนวนคดีเสพ (คดี)                                                              True
จำนวนผู้ต้องหาคดีเสพ (คน)                                                      True
จำนวนคดีครอบครอง (คดี)                                                         True
จำนวนผู้ต้องหาคดีครอบครอง (คน)                                                 True
จำนวนคดีครอบครองเพื่อจำหน่าย (คดี)                                             True
จำนวนผู้ต้องหาคดีครอบครองเพื่อจำหน่าย (คน)                                     True
จำนวนคดีจำหน่าย (คดี)                                                          True
จำนวนผู้ต้องหาคดีจำหน่าย (คน)                                                  True
จำนวนคดีผลิต (คดี)                                                             True
จำนวนผู้ต้องหาคดีผลิต (คน)                                                     True
จำนวนคดีนำเข้า (คดี)                                                           True
จำนวนผู้ต้องหาคดีนำเข้า (คน)                                                   True
จำนวนคดีส่งออก (คดี)                                                           True
จำนวนผู้ต้องหาคดีส่งออก (คน)                                                   True
จำนวนคดีสมคบ (คดี)                                                             True
จำนวนผู้ต้องหาคดีสมคบ (คน)                                                     True
จำนวนคดี 5 ข้อหาหลัก (คดี)                                                     True
จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)                                             True
dtype: bool

In [31]:
merge_3table.dropna()

    ปีงบประมาณ  ...  จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)
0         2563  ...                              5685.0
1         2563  ...                              2999.0
8         2563  ...                               564.0
13        2563  ...                               367.0
15        2563  ...                               651.0
17        2563  ...                               783.0
18        2563  ...                              2792.0
20        2563  ...                              1427.0
21        2563  ...                              2484.0
22        2563  ...                              3043.0
25        2563  ...                               855.0
26        2563  ...                               881.0
28        2563  ...                              2164.0
30        2563  ...                               913.0
31        2563  ...                               768.0
32        2563  ...                              1198.0
33        2563  ...                              1433.0
35        2563  ...                              1857.0
36        2563  ...                               834.0
37        2563  ...                               596.0
38        2563  ...                              3234.0
45        2563  ...                              1910.0
46        2563  ...                               160.0
50        2563  ...                               543.0
55        2563  ...                               976.0
56        2563  ...                              1022.0
57        2563  ...                              1037.0
62        2563  ...                              1130.0
65        2563  ...                               731.0
66        2563  ...                              2164.0
68        2563  ...                               511.0
70        2563  ...                              3366.0
71        2563  ...                               966.0
76        2563  ...                              1230.0

[34 rows x 39 columns]

In [33]:
merge_3table.shape

(77, 39)

In [32]:
merge_3table.dropna().shape

(34, 39)